### ISSUE TITLE
Could not find a declaration file for module 'telegram-inline-calendar'.

### ISSUE THREAD

**Issue by mgorodetski** [VDS13/telegram-inline-calendar#7]
I can't import 'telegram-inline-calendar' to my project properly as could not find a declaration file for module 'telegram-inline-calendar' . Tried both CommonJS and imports versions, also tried to declare module myself but it sisn't help

**Comment by VDS13** [comment]
@mgorodetski, Hi!
Can you show the error output and code?

**Comment by mgorodetski** [comment]
sure, this is import in my bot: 
![image](https://user-images.githubusercontent.com/87032361/232725956-327aaa1f-d630-49b2-8244-8a1191cbdb85.png)
same issue at node-modules: 
![image](https://user-images.githubusercontent.com/87032361/232726465-2f406183-b983-42a1-861b-b6f15e993308.png)

**Comment by VDS13** [comment]
A few more questions:
What version of the package is used on the screenshots?
Is there a `type: module` parameter in `package.json`?
Have you edited `node_modules` yourself?

**Comment by mgorodetski** [comment]
What version of the package is used on the screenshots?  "telegram-inline-calendar": "^2.0.3"
Is there a type: module parameter in package.json? yes
Have you edited node_modules yourself? no, besides adding error output in th comment

**Comment by VDS13** [comment]
The problem should be solved if in the second screen replace the line:
```js
export {Calendar} from './src/Calendar.js';
```
In `ESM`, the file format must be specified explicitly during import/export (`.js`, `.mjs`).

**Comment by VDS13** [comment]
It's just that if you look at the files of this version in `npm`, then the export is specified there correctly.
![image](https://user-images.githubusercontent.com/55276080/232731217-99b5cf1b-29f5-4f78-8301-1c22e21dafff.png)
For some reason, the screenshot from `node_modules` is wrong.
![image](https://user-images.githubusercontent.com/87032361/232726465-2f406183-b983-42a1-861b-b6f15e993308.png)

**Comment by mgorodetski** [comment]
Sorry, I forget I already tried it and didn't amend it back before replying to you above. Anyway it doesn't solve the problem: 
![image](https://user-images.githubusercontent.com/87032361/232732364-6af874a9-18e4-4c27-8b11-fd3bd45e2ea1.png)

**Comment by VDS13** [comment]
Are you using typescript?

**Comment by mgorodetski** [comment]
> Are you using typescript?

Nope, js

**Comment by VDS13** [comment]
Can you show the contents of `package.json`?

**Comment by mgorodetski** [comment]
> Can you show the contents of `package.json`?
Sure, here it is: 
![image](https://user-images.githubusercontent.com/87032361/232745609-cbcb1539-6732-4c52-8198-8d6dfbd68930.png)

**Comment by VDS13** [comment]
Does the error show up after starting the bot or only in VS Code itself?

**Comment by mgorodetski** [comment]
in VS Code itself. Just ignore that?

**Comment by VDS13** [comment]
VS Code throws this error because it uses TS. When starting the bot, there should be no problems. In the future I will release a release under TS.

**Comment by mgorodetski** [comment]
Спасибо за твой труд и за объяснения!

**Comment by VDS13** [comment]
Glad to help, @mgorodetski)
